#pragma once
#include"Operation.h"
#include"Granulating.h"
#include"Averaging.h"
#include"AddStZn.h"
#include"Granulating.h"
#include"Manipulator.h"
#include"Container.h"
#include"Cell.h"
#include"Press.h"
#include"Storage.h"
#include"Probe.h"
#include"Laba.h"
